.. Documentation for Probability Project

Welcome to Probability Project's documentation!
===============================================

.. toctree::
   :maxdepth: 2
   :caption: 目录

   第二章-随机变量及其分布/2.1_随机变量
   第二章-随机变量及其分布/2.2_离散型随机变量及其分布律

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
